import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { createInviteUrl, inviteFromHash } from "../invite-codec.js";
import {
  DEFAULT_SHARE_COPY_ID,
  DEFAULT_SHARE_ICON_ID,
  SHARE_COPIES,
  SHARE_ICONS,
  SHARE_ROUTE_LETTERS,
  shareCopyById,
  shareIconById,
  shareRoutePath,
} from "../share-options.js";

const publicRoot = "https://markjinli.github.io/hx/";
const invite = {
  personA: "短链测试甲",
  personB: "短链测试乙",
  date: "2031-09-17",
  time: "17:31",
  venue: "短链测试宴会厅",
  address: "短链测试路 31 号",
  message: "这段短链测试寄语不应出现在静态页面中。",
};

function jpegDimensions(buffer) {
  assert.equal(buffer[0], 0xff);
  assert.equal(buffer[1], 0xd8);
  let offset = 2;
  while (offset + 8 < buffer.length) {
    if (buffer[offset] !== 0xff) {
      offset += 1;
      continue;
    }
    const marker = buffer[offset + 1];
    offset += 2;
    if (marker === 0xd8 || marker === 0xd9) continue;
    const length = buffer.readUInt16BE(offset);
    if ([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf].includes(marker)) {
      return { height: buffer.readUInt16BE(offset + 3), width: buffer.readUInt16BE(offset + 5) };
    }
    offset += length;
  }
  throw new Error("JPEG dimensions not found");
}

test("defines four safe icon choices and four preset share descriptions", () => {
  assert.equal(SHARE_ICONS.length, 4);
  assert.equal(SHARE_COPIES.length, 4);
  assert.equal(new Set(SHARE_ICONS.map(({ id }) => id)).size, 4);
  assert.equal(new Set(SHARE_COPIES.map(({ id }) => id)).size, 4);
  assert.equal(shareIconById("not-an-option").id, DEFAULT_SHARE_ICON_ID);
  assert.equal(shareCopyById("not-an-option").id, DEFAULT_SHARE_COPY_ID);
  const routeLetters = Object.values(SHARE_ROUTE_LETTERS);
  assert.equal(routeLetters.length, 16);
  assert.equal(new Set(routeLetters).size, 16);
  assert.deepEqual([...routeLetters].sort(), "abcdefghijklmnop".split(""));
  assert.ok(routeLetters.every((letter) => /^[a-p]$/.test(letter)));
  assert.equal(shareRoutePath("../escape", "../escape"), "a/");
});

test("all four optimized thumbnails are square, compact JPEG files", async () => {
  for (const icon of SHARE_ICONS) {
    const image = await readFile(new URL(`../${icon.path}`, import.meta.url));
    assert.ok(image.length > 10_000, `${icon.id} should contain a real illustration`);
    assert.ok(image.length < 100_000, `${icon.id} should stay small for chat crawlers`);
    assert.deepEqual(jpegDimensions(image), { width: 512, height: 512 });
  }
});

test("a selected presentation changes only the static path while personal data stays in the hash", () => {
  const routePath = shareRoutePath("love-birds", "good-day");
  const shareUrl = createInviteUrl(new URL(routePath, publicRoot), invite);
  const parsed = new URL(shareUrl);

  assert.equal(parsed.pathname, `/hx/${routePath}`);
  assert.equal(parsed.search, "");
  assert.match(parsed.hash, /^#2\./);
  assert.doesNotMatch(`${parsed.pathname}${parsed.search}`, /短链测试甲|短链测试乙|短链测试宴会厅/);
  assert.deepEqual(inviteFromHash(parsed.hash), invite);
});

test("build emits all 16 route-specific static crawler pages", async () => {
  let count = 0;
  const generatedPaths = new Set();
  for (const icon of SHARE_ICONS) {
    for (const copy of SHARE_COPIES) {
      const routePath = shareRoutePath(icon.id, copy.id);
      assert.match(routePath, /^[a-p]\/$/);
      assert.equal(generatedPaths.has(routePath), false, `${routePath} must be unique`);
      generatedPaths.add(routePath);
      const page = await readFile(new URL(`../${routePath}index.html`, import.meta.url), "utf8");
      const routeUrl = new URL(routePath, publicRoot).href;
      const imageUrl = new URL(icon.path, publicRoot).href;

      assert.match(page, /Generated by scripts\/build-share-pages\.mjs/);
      assert.match(page, new RegExp(`data-base="\\.\\.\/" data-share-icon="${icon.id}" data-share-copy="${copy.id}"`));
      assert.ok(page.includes(`<meta property="og:description" content="${copy.text}" />`));
      assert.ok(page.includes(`<meta property="og:url" content="${routeUrl}" />`));
      assert.ok(page.includes(`<meta property="og:image" content="${imageUrl}" />`));
      assert.ok(page.includes(`<link rel="image_src" href="${imageUrl}" />`));
      assert.match(page, /<meta property="og:image:width" content="512" \/>/);
      assert.match(page, /<link rel="stylesheet" href="\.\.\/styles\.css" \/>/);
      assert.match(page, /<script type="module" src="\.\.\/app\.js"><\/script>/);
      assert.doesNotMatch(page, /src="\.\/icons\//);
      assert.match(page, /src="\.\.\/icons\//);
      if (page.includes("m.mp3")) {
        assert.match(page, /src="\.\.\/m\.mp3"/);
        assert.doesNotMatch(page, /src="\.\/m\.mp3"/);
      }
      assert.doesNotMatch(page, /短链测试甲|短链测试乙|短链测试宴会厅|短链测试路 31 号|这段短链测试寄语/);
      count += 1;
    }
  }
  assert.equal(count, 16);
});
