import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { createInviteUrl, inviteFromHash } from "../invite-codec.js";
import {
  DEFAULT_SHARE_COPY_ID,
  DEFAULT_SHARE_ICON_ID,
  SHARE_COPIES,
  SHARE_ICONS,
  SHARE_ROUTE_VERSION,
  shareCopyById,
  shareIconById,
  shareRoutePath,
} from "../share-options.js";

const publicRoot = "https://markjinli.github.io/hexi-wedding-invitation/";
const invite = {
  personA: "林知夏",
  personB: "周亦安",
  date: "2026-10-18",
  time: "18:18",
  venue: "嘉悦宴会艺术中心",
  address: "湖畔路 88 号",
  message: "诚邀您见证我们的幸福时刻。",
};

function jpegDimensions(buffer) {
  assert.equal(buffer[0], 0xff);
  assert.equal(buffer[1], 0xd8);
  let offset = 2;
  while (offset + 8 < buffer.length) {
    if (buffer[offset] !== 0xff) {
      offset += 1;
      continue;
    }
    const marker = buffer[offset + 1];
    offset += 2;
    if (marker === 0xd8 || marker === 0xd9) continue;
    const length = buffer.readUInt16BE(offset);
    if ([0xc0, 0xc1, 0xc2, 0xc3, 0xc5, 0xc6, 0xc7, 0xc9, 0xca, 0xcb, 0xcd, 0xce, 0xcf].includes(marker)) {
      return { height: buffer.readUInt16BE(offset + 3), width: buffer.readUInt16BE(offset + 5) };
    }
    offset += length;
  }
  throw new Error("JPEG dimensions not found");
}

test("defines four safe icon choices and four preset share descriptions", () => {
  assert.equal(SHARE_ROUTE_VERSION, "v2");
  assert.equal(SHARE_ICONS.length, 4);
  assert.equal(SHARE_COPIES.length, 4);
  assert.equal(new Set(SHARE_ICONS.map(({ id }) => id)).size, 4);
  assert.equal(new Set(SHARE_COPIES.map(({ id }) => id)).size, 4);
  assert.equal(shareIconById("not-an-option").id, DEFAULT_SHARE_ICON_ID);
  assert.equal(shareCopyById("not-an-option").id, DEFAULT_SHARE_COPY_ID);
  assert.equal(shareRoutePath("../escape", "../escape"), `share/v2/${DEFAULT_SHARE_ICON_ID}/${DEFAULT_SHARE_COPY_ID}/`);
});

test("all four optimized thumbnails are square, compact JPEG files", async () => {
  for (const icon of SHARE_ICONS) {
    const image = await readFile(new URL(`../${icon.path}`, import.meta.url));
    assert.ok(image.length > 10_000, `${icon.id} should contain a real illustration`);
    assert.ok(image.length < 100_000, `${icon.id} should stay small for chat crawlers`);
    assert.deepEqual(jpegDimensions(image), { width: 512, height: 512 });
  }
});

test("a selected presentation changes only the static path while personal data stays in the hash", () => {
  const routePath = shareRoutePath("love-birds", "good-day");
  const shareUrl = createInviteUrl(new URL(routePath, publicRoot), invite);
  const parsed = new URL(shareUrl);

  assert.equal(parsed.pathname, `/hexi-wedding-invitation/${routePath}`);
  assert.equal(parsed.search, "");
  assert.match(parsed.hash, /^#i=v1\./);
  assert.doesNotMatch(`${parsed.pathname}${parsed.search}`, /林知夏|周亦安|嘉悦/);
  assert.deepEqual(inviteFromHash(parsed.hash), invite);
});

test("build emits all 16 route-specific static crawler pages", async () => {
  let count = 0;
  for (const icon of SHARE_ICONS) {
    for (const copy of SHARE_COPIES) {
      const routePath = shareRoutePath(icon.id, copy.id);
      const page = await readFile(new URL(`../${routePath}index.html`, import.meta.url), "utf8");
      const routeUrl = new URL(routePath, publicRoot).href;
      const imageUrl = new URL(icon.path, publicRoot).href;

      assert.match(page, /Generated by scripts\/build-share-pages\.mjs/);
      assert.match(page, new RegExp(`data-base="\\.\\.\/\\.\\.\/\\.\\.\/\\.\\.\/" data-share-icon="${icon.id}" data-share-copy="${copy.id}"`));
      assert.ok(page.includes(`<meta property="og:description" content="${copy.text}" />`));
      assert.ok(page.includes(`<meta property="og:url" content="${routeUrl}" />`));
      assert.ok(page.includes(`<meta property="og:image" content="${imageUrl}" />`));
      assert.ok(page.includes(`<link rel="image_src" href="${imageUrl}" />`));
      assert.match(page, /<meta property="og:image:width" content="512" \/>/);
      assert.match(page, /<link rel="stylesheet" href="\.\.\/\.\.\/\.\.\/\.\.\/styles\.css" \/>/);
      assert.match(page, /<script type="module" src="\.\.\/\.\.\/\.\.\/\.\.\/app\.js"><\/script>/);
      count += 1;
    }
  }
  assert.equal(count, 16);
});
